version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "eritger1110"
    assignees:
      - "eritger1110"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "eritger1110"
    assignees:
      - "eritger1110"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Allow security updates for major versions
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "flask"
        update-types: ["version-update:semver-major"]
      - dependency-name: "gunicorn"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies (if package.json exists)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "eritger1110"
    assignees:
      - "eritger1110"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Versioning strategy for npm
    versioning-strategy: "increase"
