version: 2
updates:
  # Python runtime and application dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    reviewers:
      - "eritger1110"
    assignees:
      - "eritger1110"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # Group Python runtime libraries together
      python-runtime:
        patterns:
          - "flask*"
          - "pydantic*"
          - "bcrypt*"
          - "cryptography*"
          - "gunicorn*"
          - "requests*"
          - "psycopg*"
          - "sqlalchemy*"
          - "marshmallow*"
          - "stripe*"
          - "sendgrid*"
          - "pyjwt*"
        update-types:
          - "minor"
          - "patch"
      # Group testing and development tools
      python-tooling:
        patterns:
          - "pytest*"
          - "bandit*"
          - "black*"
          - "flake8*"
          - "mypy*"
          - "coverage*"
        update-types:
          - "minor"
          - "patch"
    # Allow security updates for all dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates for critical dependencies
    ignore:
      - dependency-name: "flask"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"
    reviewers:
      - "eritger1110"
    assignees:
      - "eritger1110"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # Group all GitHub Actions together
      ghactions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Node.js dependencies (if package.json exists in future)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    reviewers:
      - "eritger1110"
    assignees:
      - "eritger1110"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # Group Node.js runtime dependencies
      npm-runtime:
        patterns:
          - "express*"
          - "react*"
          - "next*"
          - "typescript*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      # Group Node.js tooling dependencies
      npm-tooling:
        patterns:
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "@testing-library/*"
          - "webpack*"
          - "vite*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: "increase"
