version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: brikk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - brikk-local

volumes:
  redis_data:
    driver: local

networks:
  brikk-local:
    driver: bridge
