name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual security scan'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep Security Scan
    permissions:
      contents: read
    # Always run Semgrep to catch security issues across all file types
    steps:
    - uses: actions/checkout@v4

    - name: Semgrep (scan)
      uses: returntocorp/semgrep-action@v1
      with:
        config: >
          p/owasp-top-ten
          p/secrets
          p/python
          p/flask
          p/security-audit
        generateSarif: false
      env:
        SEMGREP_TIMEOUT: 180

  secret-scan:
    runs-on: ubuntu-latest
    name: Secret Pattern Detection
    permissions:
      contents: read
    # Always run secret scanning to prevent credential leaks
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Gitleaks (download binary)
      run: |
        set -euo pipefail
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_${OS}_x64.tar.gz -o gl.tgz
        tar -xzf gl.tgz gitleaks
        ./gitleaks version

    - name: Gitleaks (scan workspace, capture result)
      id: gitleaks
      run: |
        set -euo pipefail
        # Run detect but don't fail the step yet; we'll inspect the report explicitly
        ./gitleaks detect \
          --no-banner \
          --redact \
          --report-path gitleaks.json \
          --report-format json \
          --log-opts="--no-merges" || true

        # If report exists, fail only when leaks > 0
        if [ -f gitleaks.json ]; then
          python - <<'PY'
import json,sys
data=json.load(open('gitleaks.json'))
leaks = data.get('leaks', [])
print(f"gitleaks: {len(leaks)} leaks")
sys.exit(1 if leaks else 0)
PY
        else
          echo "No report produced (likely infra/billing hiccup) → mark neutral"
          exit 0
        fi

  dependency-check:
    runs-on: ubuntu-latest
    name: OWASP Dependency Check
    permissions:
      contents: read
    # Skip for now - will re-enable when manifests exist
    if: false
    steps:
    - uses: actions/checkout@v4

    - name: OWASP DC (scan)
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'brikk-infrastructure'
        path: '.'
        format: 'ALL'
        args: >
          --enableRetired
          --enableExperimental
          --failOnCVSS 7

    - name: Upload Dependency Check results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: reports/
      continue-on-error: true
