name: Trivy Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  trivy-repo-scan:
    runs-on: ubuntu-latest
    name: Trivy Repository Scan
    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-repo-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-repo-results.sarif'

    - name: Run Trivy vulnerability scanner (table format)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

  trivy-docker-scan:
    # Guard to avoid failing on repos that don't yet contain Docker infrastructure
    if: ${{ hashFiles('Dockerfile', 'server/Dockerfile', 'infra/**') != '' }}
    runs-on: ubuntu-latest
    name: Trivy Docker Image Scan
    steps:
    - uses: actions/checkout@v4

    - name: Find Dockerfile
      run: |
        # Find the Dockerfile to use
        if [ -f Dockerfile ]; then
          echo "DOCKERFILE_PATH=Dockerfile" >> $GITHUB_ENV
        elif [ -f server/Dockerfile ]; then
          echo "DOCKERFILE_PATH=server/Dockerfile" >> $GITHUB_ENV
        else
          echo "No Dockerfile found"
          exit 1
        fi

    - name: Build Docker image
      run: |
        docker build -f ${{ env.DOCKERFILE_PATH }} -t brikk-infrastructure:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner on Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'brikk-infrastructure:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-docker-results.sarif'

    - name: Upload Trivy Docker scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-docker-results.sarif'

    - name: Run Trivy vulnerability scanner on Docker image (fail on high/critical)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'brikk-infrastructure:${{ github.sha }}'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

  trivy-config-scan:
    runs-on: ubuntu-latest
    name: Trivy Configuration Scan
    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy configuration scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-config-results.sarif'

    - name: Upload Trivy config scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-config-results.sarif'

    - name: Run Trivy configuration scanner (table format)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'table'
        severity: 'CRITICAL,HIGH'
