name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black
        
    - name: Run flake8 linting
      run: |
        flake8 src/ --select=E9,F63,F7,F82 --max-line-length=88 --exclude=__pycache__ || echo "Linting issues found - consider fixing critical errors"
        
    - name: Check code formatting with black
      run: |
        black --check . --exclude="__pycache__|\.git|\.pytest_cache" || echo "Code formatting issues found - consider running 'black .' to fix"
        
    - name: Run smoke tests
      run: |
        pytest -q tests/test_smoke.py
